//! Trusted process adapters for Revoot.

#![forbid(unsafe_code)]

pub mod completion;
pub mod config;
pub mod credentials;
pub mod delegate_command;
pub mod diff_artifact;
pub mod egress_setup;
mod embedded_git;
pub mod git_history;
pub mod github_checkout;
pub mod github_init;
pub mod github_review;
pub mod github_transport;
pub mod gitlab_checkout;
pub mod gitlab_ci_runtime;
pub mod gitlab_incremental;
pub mod gitlab_init;
pub mod gitlab_publication;
pub mod gitlab_review_context;
pub mod gitlab_snapshot;
pub mod gitlab_transport;
pub mod group_runtime;
pub mod group_scheduler;
pub mod group_worker_engine;
pub mod grouping;
pub mod local_review;
pub mod mcp_server;
pub mod prior_review;
pub mod providers;
pub mod review_adjudicator;
pub mod review_checkpoint;
pub mod review_command;
pub mod review_engine;
pub mod review_group_execution;
pub mod review_group_inputs;
pub mod review_group_packet;
pub mod review_grouper;
pub mod review_overview;
pub mod review_preparation;
pub mod review_result_reducer;
pub mod review_rule_bundle;
pub mod review_rules;
pub mod review_strategy_config;
pub mod review_verifier;
pub mod rule_diagnostics;
pub mod rules_command;
pub mod scan_command;
